### ISSUE TITLE
Darstellungsprobleme beim Internet Explorer

### ISSUE THREAD

**Issue by JWeha** [cosmocode/dokuwiki-template-sprintdoc#10]
Hallo zusammen,

ich habe Ihr Template bei DokuWiki gefunden und bin begeistert. Leider habe ich eine Unschärfe festgestellt. Wenn ich das Template auf meinem Notebook mit dem Internet Explorer öffne, dann werden bestimmte Icons nicht richtig dargestellt:
 
![1](https://user-images.githubusercontent.com/41040709/42492871-f64c5fb6-841a-11e8-89a2-a75767db38cc.png)

Meine Internet Explorer Version ist:

![2](https://user-images.githubusercontent.com/41040709/42492891-1133ab04-841b-11e8-9d41-b5e2cf811047.png)

Mein OS ist:
 
![3](https://user-images.githubusercontent.com/41040709/42492921-3075b44e-841b-11e8-88f4-1543e21fee80.png)

Können Sie mir weiterhelfen? Bei allen anderen Browsern funktioniert das Template sehr gut. Leider bin ich gezwungen, den Internet Explorer hierfür zu benutzen.

Mit freundlichen Grüßen / Best Regards

Jens Wehage

**Comment by micgro42** [comment]
It seems like the external font is not loading correctly. Could it be that you are using the IE in compatibility mode or some "high security" setting enabled?

**Comment by JWeha** [comment]
Hello, Michael,

thank you for the quick reply. After adding the website to the Trusted Websites, the display now works correctly.

Mit freundlichen Grüßen / Best Regards

Jens Wehage

Jens Wehage | CGI | Senior Consultant
CGI Deutschland Ltd. & Co. KG
Kranhaus, Hoerneckestraße 39 | 28217 Bremen | Germany
T: +49 421 5491 349  | F:+49 421 5491 51 349
Jens.Wehage@cgi.com<mailto:Vorname.Nachname@cgi.com> | de.cgi.com<http://www.de.cgi.com/>

CGI folgen auf: Xing<https://www.xing.com/companies/cgi> | LinkedIn<https://www.linkedin.com/company/cgi> | Twitter<https://twitter.com/cgi_de> | Facebook<https://www.facebook.com/CGIDeutschland>
Unsere Pflichtangaben gemäß § 35a GmbHG / §§ 161, 125a HGB finden Sie unter de.cgi.com/pflichtangaben<http://de.cgi.com/pflichtangaben>.

CONFIDENTIALITY NOTICE: Proprietary/Confidential information belonging to CGI Group Inc. and its affiliates may be contained in this message. If you are not a recipient indicated or intended in this message (or responsible for delivery of this message to such person), or you think for any reason that this message may have been addressed to you in error, you may not use or copy or deliver this message to anyone else. In such case, you should destroy this message and are asked to notify the sender by reply e-mail.

[cid:image002.jpg@01CF9149.E7BD3290]     [cid:image003.gif@01CF9149.E7BD3290]

Von: Michael Große <notifications@github.com>
Gesendet: Dienstag, 10. Juli 2018 10:43
An: cosmocode/dokuwiki-template-sprintdoc <dokuwiki-template-sprintdoc@noreply.github.com>
Cc: Wehage, Jens <jens.wehage@cgi.com>; Author <author@noreply.github.com>
Betreff: Re: [cosmocode/dokuwiki-template-sprintdoc] Darstellungsprobleme beim Internet Explorer (#10)


It seems like the external font is not loading correctly. Could it be that you are using the IE in compatibility mode or some "high security" setting enabled?

**Comment by micgro42** [comment]
:+1:
