### ISSUE TITLE
sidebar with @ in title

### ISSUE THREAD

**Issue by stblassitude** [cosmocode/dokuwiki-template-sprintdoc#104]
I would like to have a sidebar entry like this:

```
====== @c3toc@chaos.social @wiki:mastodon.svg ======
```

I've uploaded mastodon.svg to the wiki namespace, and the icon is shown correctly **if I don't have at signs in the title**. The version I'm using now is 
```
====== Mastodon c3toc at chaos.social @wiki:mastodon.svg ======
```

I've tried various escape methods for the at sign, but couldn't get it to work. Any hints?

**Comment by stblassitude** [comment]
The site is here: https://c3toc.de/doku.php?id=start

**Comment by annda** [comment]
At this point "@" is reserved for icons. There is no escaping.
