### ISSUE TITLE
Suggestion location page TOC (to the left)

### ISSUE THREAD

**Issue by martk70** [cosmocode/dokuwiki-template-sprintdoc#11]
Page TOC link on the left instead of far right (desktop)?
I think this could be more intuitive next to the sidebar (navigation always on the left) and easier to find for new users.

**Comment by ivangretsky** [comment]
Hey, @martk70 !

Being on the left side it is more likely to hide the start of lines, which is more import for the reader to his way. As for me, the TOC flag is pretty evident where it is)
