### ISSUE TITLE
2024-03-12 insufficient "Configuration Metadata"

### ISSUE THREAD

**Issue by Zweihorn** [cosmocode/dokuwiki-template-sprintdoc#110]
### Issue Description

Using the current "Kaos" [55.1] with the current _sprintdoc_ 2024-03-12 template produces a "**E_WARNING: Undefined array key 0**" warning in the log file when the "Configuration Settings" page is accessed.

The culprit was  found as the insufficient "Configuration Metadata" in file `lib/tpl/sprintdoc/conf/metadata.php` last line. 

After changing the last line to `$meta['copyright'] = array('');` there is no warning in the log file. The "Configuration Settings" page works without issue and shows the intended behaviour with the "tpl»sprintdoc»copyright" setting.

The a.m. syntax change is in accordance with https://www.dokuwiki.org/devel:configuration#classes and provides a "Default class ('setting'), textarea" definition. This avoids the 'null' reference and should meet the expectations.

See https://github.com/dokuwiki/dokuwiki/issues/4252 for full bug report and https://github.com/dokuwiki/dokuwiki/issues/4252#issuecomment-2028188483 for my proposed solution.

Voila.
🌻

**Comment by splitbrain** [comment]
You're right. Can you open a PR please?

**Comment by splitbrain** [comment]
never mind. I overlooked that you already did :-)
