### ISSUE TITLE
Illegal string offset bug in main.php line 20

### ISSUE THREAD

**Issue by ichris007** [cosmocode/dokuwiki-template-sprintdoc#12]
there is a bug prompt:
Illegal string offset 'sprintdoc' in /dokuwiki/lib/tpl/sprintdoc/main.php on lien 20

**Comment by micgro42** [comment]
Thank you for reporting this! 👍

It appears to be an conflict with ckgedit:
https://codesearch.dokuwiki.org/xref/plugin/ckgedit/action/meta.php#787

Once you deactivate that plugin it should work fine.

Feel free to report this error at the ckgedit repository :)

**Comment by ichris007** [comment]
@micgro42 I have to use the plugin ckgedit as WYSIWYG editor, could you resolve the conflict?

**Comment by turnermm** [comment]
There was a naming conflict and I've changed the name in ckgedit.

**Comment by turnermm** [comment]
@micgro42  how did you determine that 787 causes a conflict?  It's a simple assignment of JSINFO array element to a $conf element.

**Comment by turnermm** [comment]
There was a naming conflict, and it was a bit naive of both of us to use a wide-open  key for JSINFO like `template`. I changed it in ckgedit, which was a simple fix.

**Comment by micgro42** [comment]
Exactly, we tried to use the key `$JSINFO['template']` as an array/object, analogous to `$JSINFO['plugins']`, in which to set the js-settings for this template. However, ckgedit already set this key to a string, thus the error.
Both are plausible use-cases of that key.

**Comment by ichris007** [comment]
@micgro42 @turnermm Thanks to you both. 
I'm not a coder, just a user, could you tell me how to change the name in Ckgedit?

**Comment by micgro42** [comment]
@ichris007 Updating the plugin should be enough :)

**Comment by ichris007** [comment]
@micgro42 Thanks a lot!
