### ISSUE TITLE
Cannot show logo

### ISSUE THREAD

**Issue by patrickTingen** [cosmocode/dokuwiki-template-sprintdoc#15]
Hi, I just discovered this beautiful theme, but I fail to get a logo in my upper left corner. I found the [documentation ](https://www.dokuwiki.org/template:sprintdoc#configuration) on this and it says:

> The template supports various logos, favicons etc. They have to be provided in PNG format and need to be uploaded to the wiki namespace.

I uploaded a file "logo-wide.png" to my wiki namespace, but I don't see it on the wiki itself. Am I doing something wrong or is this a bug?

**Comment by splitbrain** [comment]
You probably did something wrong, then. But there's not enough info to tell you what.
