### ISSUE TITLE
Option to hide header

### ISSUE THREAD

**Issue by natrius** [cosmocode/dokuwiki-template-sprintdoc#17]
I would like to hide the header so less space at the top is wasted (just my opinion :D ) - an option would be nice, otherwise i would have to hide via some fileediting directly - an option would be preferred.

**Comment by splitbrain** [comment]
@JayDeeDee I had a few customers mentioning the "wasted space" of the header. Personally I don't agree, but especially when using a square logo, a short wiki title and no tag line it seems to be quite empty indeed.

Maybe we could have a "compact layout" option where we omit the tagline, move the logo and title up and remove some whitespace?

![screenshot-cosmocode wiki-2019 02 18-13-57-23](https://user-images.githubusercontent.com/86426/52952606-59192d80-3385-11e9-9c37-ca19aaa2e662.png)

**Comment by natrius** [comment]
And here, using it for private usage, i don't use a logo and basically no Title too. If you want, i can provide a screen too :)
