### ISSUE TITLE
Multi-language switcher support?

### ISSUE THREAD

**Issue by poVoq** [cosmocode/dokuwiki-template-sprintdoc#18]
Many themes for Dokuwiki support the really nice official translations plugin, but this one doesn't seem to have an option to switch languages if they are added in the settings.

Would be nice to have that :) Thanks for considering it.

**Comment by estorado** [comment]
I think this is solved;
https://github.com/cosmocode/dokuwiki-template-sprintdoc/commit/cfa8d1441b36fba29dc29fb47d4bed402be1b238
