### ISSUE TITLE
Warning: Cannot modify header information error in Greebo

### ISSUE THREAD

**Issue by shivahnshankar** [cosmocode/dokuwiki-template-sprintdoc#2]
On a clean install of Greebo, when I choose the sprintdoc template, I get the following error:
**Warning**: Cannot modify header information - headers already sent by **(/path/to/tpl/sprintdoc/main.php:1) in /path/to/tpl/sprintdoc/main.php on line 15**

**Comment by micgro42** [comment]
Thanks for catching this, it should be resolved now :+1:
