### ISSUE TITLE
Remove unneeded JS dependencies

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-template-sprintdoc#26]
We currently load a bunch of JS files where it is not entirely clear that we need them.

* html5shiv - we only support IE11+, do we really need this?
* velocity - I don't know what we use this for, but I think jQueryUI should provide enough animation stuff to use?
* spc.js - what does this do?
* rem.min.js - what does this do?
* respond.min.js - what does this do?
* plugins/* - there seem to be some scripts suppressing errors in plugins here? why exactly is that necessary? shouldn't rather the plugin being fixed?

**Comment by ivangretsky** [comment]
I can see a bunch of commits dealing with the issue. Can it be closed?
