### ISSUE TITLE
positioning of search tool 

### ISSUE THREAD

**Issue by tinalegre** [cosmocode/dokuwiki-template-sprintdoc#28]
I was wondering whether it's possible to easily change the position of "search-tool" and place it just below the "user tool buttons" on the top right corner?

**Comment by splitbrain** [comment]
Can you explain your motivation?

**Comment by tinalegre** [comment]
It's to have the flexibility to change the layout a bit. As a user, it seems to me more natural to have only on the left sidebar the links (to wikipages, sitemap, etc), while if I've to look for something, I would prefer to have it clearly separated. From the sprintdoc layout, inserting the "search function"  on the top-right corner below the "user tool buttons" seemed to be the perfect match.

**Comment by splitbrain** [comment]
Sorry, I don't see the benefit.
