### ISSUE TITLE
Add support for pagetitle

### ISSUE THREAD

**Issue by Belphemur** [cosmocode/dokuwiki-template-sprintdoc#3]
Hello,

This is a great template, a modern version of DokuWiki original theme, I love it.

Could you add support for [PageTitle](https://www.dokuwiki.org/plugin:pagetitle)

The plugin let the user setup a title for the base without having to sacrifice the H1 for it.

**Comment by micgro42** [comment]
I'm not sure I understand the purpose of the plugin. What is wrong with using a 1st-level heading (i.e. `====== Your heading here ======`) for the page title?

Or this more about the about being able to use some formatting in the title?

**Comment by micgro42** [comment]
Also, what would be needed to support this plugin? Why doesn't it work out-of-the-box?

**Comment by Belphemur** [comment]
Not using the H1 is to avoid having it in the table of content, the
title doesn't really need to be present there.
The thing is, if I edit the page while using your theme, the
<title></title> won't appear, it only appears if I edit the page with
the bootstrap theme ...
I don't understand why it does act this way.
This mean, if I edit the page with the bootstrap theme, then view the
same page with your theme, the title is showing normally.
