### ISSUE TITLE
Missing checkboxes in Media Revisions

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-template-sprintdoc#39]
In the Media-Manager, usually revisions can be selected by checkboxes:

![screenshot-www dokuwiki org-2019 04 15-16-03-12](https://user-images.githubusercontent.com/86426/56138958-3461c080-5f98-11e9-9116-49225669ca26.png)

Those checkboxes are not visible in the sprintdoc template for some reason:

![screenshot-cosmocode wiki-2019 04 15-16-02-51](https://user-images.githubusercontent.com/86426/56138957-33c92a00-5f98-11e9-9ee9-7ad01d65821b.png)

**Comment by ivangretsky** [comment]
I can see the pull request merged, I checked my install and this bug seems to be fixed. Shouldn't you close it, @splitbrain ?
