### ISSUE TITLE
changing header colors sprintdoc + ckgedit plugin

### ISSUE THREAD

**Issue by tinalegre** [cosmocode/dokuwiki-template-sprintdoc#41]
I managed to change through .css the default color of the headers (h1->h6) from black to red by adapting the `lib/tpl/sprintdoc/css/base_design.less` file and by adding a new variable `@ini_header_color` in `lib/tpl/sprintdoc/style.ini` file.

The `style.ini`has now the following line:
`__header_color = red ; @init_header_color`
and the `base_design.less`:
`h1,h2,h3,h4,h5,h6{
 ....
    color:  @init_header_color
....
}`

I am also using the `ckgedit` plugin whose default headers are black (`/lib/plugins/ckgedit/ckeditor/contents.css.unc`). How could I also warranty that while editing the page content in `ckgedit`, the headers also use the `@ini_header_color` variable? I noticed, for instance, that the sprintdoc has a directory named `css/plugins`, where apparently the plugins are configured. I therefore created a new file named `ckgedit.less` and included it into the `lib/tpl/sprintdoc/style.ini` file. So far, I was not able to succeed. Is this the correct way? or what other options do there exist?

**Comment by splitbrain** [comment]
Sorry this has nothing to do with the sprintdoc plugin. In general questions like this are better asked in the forum than on github.
