### ISSUE TITLE
Unable to get logo working

### ISSUE THREAD

**Issue by SituatedAction** [cosmocode/dokuwiki-template-sprintdoc#44]
Hi there - I am new to dokuWiki and love this theme, but also struggling. I see in the documentation that I need to put my logo files into my namespace, but to be honest the phrasing isn't helping me. I know it's due to being new.

I'm trying to find out what my namespace would be - my presumption is it would be the file structure behind my wiki, and my hunch my namespace is "RetroWiki" from the path below...
dokuWiki > RetroWiki

I've tried putting logo.png (150x150px) into both dokuWiki and the RetroWiki folders, but neither has any effect. I even tried the Images directory I found buried...

Please help. No doubt it's just me not knowing the definition of what 'namespace' means, and is, and I've exhausted all I can myself to figure it out. I even went to Configuration and looked at each thing that said "namespace" to get a hint... nothing.

Thanks in advance!

**Comment by ivangretsky** [comment]
Hey, @SituatedAction !
You can use the in-built [media manger](https://www.dokuwiki.org/media_manager) for that. Once you open it, the [namespace](https://www.dokuwiki.org/namespaces) thing will be clear to you. In this theme the media manager is in the sidebar,

**Comment by splitbrain** [comment]
Specifically it's not "your namespace" it's the namespace named `wiki`

**Comment by SituatedAction** [comment]
No worries at all; this issue I asked is 25 months old at this time. I've long moved one, but thank you for you time... unfortunately just too delayed to have been of use... I didnt realize just how long it would be. No worries, though.
