### ISSUE TITLE
Dutch language

### ISSUE THREAD

**Issue by HMJR** [cosmocode/dokuwiki-template-sprintdoc#45]
Last Visited Pages is in Dutch: Laatst bezochte pagina's
If help is needed for translation into Dutch contact me

Regards,
Henk

**Comment by splitbrain** [comment]
I added the template to the translation hub. You can submit Dutch translations at https://translate.dokuwiki.org/translate/template/sprintdoc?lang=nl

**Comment by HMJR** [comment]
Hello Andreas,

 

Yesterday I finished and submitted the English-Dutch translation of the sprintdoc template.

Can you inform me that everything has been received and when the translation will become available?

Best regards,

 

Henk Meinsma

 

Van: Andreas Gohr [mailto:notifications@github.com] 
Verzonden: donderdag 20 juni 2019 16:32
Aan: cosmocode/dokuwiki-template-sprintdoc <dokuwiki-template-sprintdoc@noreply.github.com>
CC: HMJR <webmaster@offi.info>; Author <author@noreply.github.com>
Onderwerp: Re: [cosmocode/dokuwiki-template-sprintdoc] Dutch language (#45)

 

I added the template to the translation hub. You can submit Dutch translations at https://translate.dokuwiki.org/translate/template/sprintdoc?lang=nl
