### ISSUE TITLE
logo.png error on log-in-screen in a a closed wiki

### ISSUE THREAD

**Issue by thirdnote3** [cosmocode/dokuwiki-template-sprintdoc#52]
I would use the dokuwiki in closed mode (access to the content only for logged in users). 
When you already logged in the logo.png at the left in the top is visible. But on the log-in-page there is only a "?" instead of the logo.png, which means that the file couldn't be loaded correctly. What to do?

**Comment by thirdnote3** [comment]
* when i use the dokuwiki as open access there is no problem with the logo...

**Comment by splitbrain** [comment]
When you want to have unauthenticated users being able to see the logo, you need to configure ACLs for the containing namespace accordingly. Eg. give `read` permissions to `@ALL` for the `wiki` namespace. This is not sprintdoc specific btw.

**Comment by thirdnote3** [comment]
Oh. Sorry. Works pretty good :)
