### ISSUE TITLE
Problems with sprintdoc templates

### ISSUE THREAD

**Issue by siemersr** [cosmocode/dokuwiki-template-sprintdoc#58]
Hello,

we use the sprintdoc template and we have this error message: "The sqlite helper plugin could not be found."
How can we solve this problem?

**Comment by ivangretsky** [comment]
Hey, @siemersr !
I think this issue is probably not related to the template, but rather to some plugin. Anyway, try installing the [mentioned plugin](https://www.dokuwiki.org/plugin:sqlite).
