### ISSUE TITLE
Question about breadcrumbs

### ISSUE THREAD

**Issue by silvyn** [cosmocode/dokuwiki-template-sprintdoc#6]
Hello,

It's not a real issues, but I just discover your beautiful work with Sprintdoc template, and wander how to put a breadcrums like demo on https://demo.sprintdoc.de

I've read the doc https://www.dokuwiki.org/template:sprintdoc but even whith plugin, I can' find how to achieve that.

Thanks

**Comment by natrius** [comment]
It should work this way:

Settings - configuration settings - Category: Display
breadcrumbs: 0
youarehere: checked

If this works, you can close the issue :)

**Comment by silvyn** [comment]
Yes ! Thank you :)
