### ISSUE TITLE
invisible paragraph edit buttons

### ISSUE THREAD

**Issue by KaiMartin** [cosmocode/dokuwiki-template-sprintdoc#65]
Paragraph edit buttons seem to be invisible on our dokuwiki instance (greebo).The paragraph edit buttons show up and can be clicked on mouse-over. The global edit button in page tools is not affected. Is this the intended behaviour?
Is there a straight forward way to make the paragraph edit buttons visible?

**Comment by KaiMartin** [comment]
Successfully upgraded to hogfather now. Unfortunately, edit buttons are still invisible.
Any hint where to look for the problem?

**Comment by commagray** [comment]
My test wiki is affected by the same issue. It uses https://github.com/linuxserver/docker-dokuwiki container of DokuWiki.

In the default configuration yourwiki.com/lib/tpl/sprintdoc/svg.php?svg=pencil.svg&f=existing returns this instead of pencil SVG.

![Screenshot from 2021-01-20 13-39-16](https://user-images.githubusercontent.com/27947961/105169987-fa3a3100-5b24-11eb-801e-1cbce2ab6179.png)

The same URL using demo.ickewiki.de returns the correct thing.

![image](https://user-images.githubusercontent.com/27947961/105170170-379ebe80-5b25-11eb-8161-affad0c29122.png)

Maybe this is a web server issue?

**Comment by commagray** [comment]
Tried another container, now from Bitnaimi. https://github.com/bitnami/bitnami-docker-dokuwiki

It showed me a useful error.

```
10.88.0.1 - - [20/Jan/2021:12:17:07 +0000] "GET /lib/tpl/sprintdoc/svg.php?svg=pencil.svg&f=existing HTTP/1.1" 500 -
[Wed Jan 20 12:17:07.319966 2021] [php7:warn] [pid 214] [client 10.88.0.1:40316] PHP Warning:  require_once(/bitnami/dokuwiki/lib/tpl/sprintdoc/../../../vendor/autoload.php): failed to open stream: No such file or directory in /opt/bitnami/dokuwiki/inc/init.php on line 199, referer: https://wiki.innereq.org/lib/exe/css.php?t=sprintdoc&tseed=3eab15bd4f30a0c79c3e0492460aacf8
[Wed Jan 20 12:17:07.320035 2021] [php7:error] [pid 214] [client 10.88.0.1:40316] PHP Fatal error:  require_once(): Failed opening required '/bitnami/dokuwiki/lib/tpl/sprintdoc/../../../vendor/autoload.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/dokuwiki/inc/init.php on line 199, referer: https://wiki.innereq.org/lib/exe/css.php?t=sprintdoc&tseed=3eab15bd4f30a0c79c3e0492460aacf8
```

So this is an issue with directories. Bitnami uses `/bitnami/dokuwiki` for persistent storage and `/opt/bitnami/dokuwiki` for the rest of distribution that is stateless. I've just symlinked needed paths for a test, and it worked.

```
1001@d07854416bab:/bitnami/dokuwiki$ ln -sf /opt/bitnami/dokuwiki/inc .
1001@d07854416bab:/bitnami/dokuwiki$ ln -sf /opt/bitnami/dokuwiki/vendor .
```

**Comment by WebFreak001** [comment]
I've got a fork (with a PR) open that fixes this issue by installing php7-dom, which you can build if you want to replace the docker-dokuwiki image.

The problem was that the `dom_import_simplexml` function was not defined, which comes with the `php-dom` package on that linux distro.

**Comment by splitbrain** [comment]
added info on the SimpleXML requirement to the wiki page
