### ISSUE TITLE
Uncaught RuntimeException: action disabled: login in /opt/app/dokuwiki/inc/Menu/Item/AbstractItem

### ISSUE THREAD

**Issue by diomat** [cosmocode/dokuwiki-template-sprintdoc#67]
Hi,

I have Dokuwiki (Version 2020-07-29~2020-08-31 Hogfather) installed on Sandstorm ([sandstorm.io](https://sandstorm.io)). So this might be Sandstorm related but I thought I would ask here first.

After installing your template and activating it I get an error and the wiki is no longer usable (no big deal since it's new and empty though).  Clicking the "Admin" Link for example doesn't do anything.

![grafik](https://user-images.githubusercontent.com/6215791/102764479-7d783380-437b-11eb-9d7b-8a359a5218f4.png)

```
2020/12/21 09:21:09 [error] 844#844: *258 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: action disabled: login in /opt/app/dokuwiki/inc/Menu/Item/AbstractItem.php:67
Stack trace:
#0 /opt/app/dokuwiki/inc/Menu/Item/Login.php(15): dokuwiki\Menu\Item\AbstractItem->__construct()
#1 /var/lib/dokuwiki/lib/tpl/sprintdoc/tpl/nav-usertools-buttons.php(14): dokuwiki\Menu\Item\Login->__construct()
#2 /var/lib/dokuwiki/lib/tpl/sprintdoc/main.php(264): include('/var/lib/dokuwi...')
#3 /opt/app/dokuwiki/inc/actions.php(27): include('/var/lib/dokuwi...')
#4 /opt/app/dokuwiki/doku.php(122): act_dispatch()
#5 {main}
  thrown in /opt/app/dokuwiki/inc/Menu/Item/AbstractItem.php on line 67" while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /start?do=admin&page=config HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm7.0.sock:", host: "ui-77b9a80560e1de99e07df048479e1bc0.linux1:6080"
```

Any idea why error is happening or should I ask the Sandstorm people first?

Cheers

**Comment by gno65** [comment]
Hi,
I have the same error as user diomat. (#67)

You'll get this error if logout is disabled in an auth plugin ($this->cando['logout'] = false).
This will raise an exception in inc/Menu/Item/Login.php.
The exception is not catched in lib/tpl/sprintdoc/tpl/nav-usertools-buttons.php

Guido

**Comment by splitbrain** [comment]
Same as #81
