### ISSUE TITLE
More configuration/customization. 

### ISSUE THREAD

**Issue by takuy** [cosmocode/dokuwiki-template-sprintdoc#7]
I think this template looks great, but has some usability/configuration things that stop me from using it. Key things:

Need to be able to configure it similar to [Bootstrap3](https://www.dokuwiki.org/template:bootstrap3) - be able to hide last modified, path to file, last user who edited. 

I would also like to disable OR set a default state of the collapsible sidebar. 

Would also be interesting to see better integration with the Indexmenu. I prefer autogenerated menus like that...if there's an alternative that already works well, please let me know.

I might also look into doing some of these things myself.

**Comment by ivangretsky** [comment]
Hey @takuy !

Did you find time to work on modifications to the theme? Please make a pull request if you did.

**Comment by nvcleemp** [comment]
Incidentally, I was exactly looking for this feature, so I am also interested in knowing any possible progress. More specifically, I am looking for the ability to fully expand the sidebar.

**Comment by takuy** [comment]
Unfortunately, no, I never quite found the time to customize this for my own needs. The Bootstrap3 template is pretty flexible and I've just chosen to use that and customize with CSS/JS as needed. The Argon template looks pretty nice too, but not sure how well it integrates with everything else at this point.

**Comment by splitbrain** [comment]
sidebar state can now be configured. in general, we add features only when customers need them.
