### ISSUE TITLE
Missing support for plugin diagrams

### ISSUE THREAD

**Issue by schmal22** [cosmocode/dokuwiki-template-sprintdoc#70]
Hallo,

I cannot find the links/buttons to create or edit a diagram.
Due to documentation of the [plugin diagrams](https://www.dokuwiki.org/plugin:diagrams) there suppose to be a link inside the media manager to create a diagram after selecting a namespace. 

Using a different template things are working fine.

Is it a bug or am I doing something wrong?

Regard
Schmal22

**Comment by splitbrain** [comment]
Works for me.
