### ISSUE TITLE
The wiki logo can only be shown after "Log in"

### ISSUE THREAD

**Issue by albertvilabsc** [cosmocode/dokuwiki-template-sprintdoc#71]
Hi all,
I have my dokuwiki working with the sprintdoc template but the wiki logo only be shown after login.
My wiki is private but I will like to show the logo in the login page. I don’t can put the wiki namespace (My logo is there) open or in read mode because I have some important wikis in the wiki namespace.
I made tests and if I open the wiki namespace, yes, the logo appears in the login page. But if I don’t open the namespace, showed a broken link where the logo was supposed to appear on the login screen.
Any of you have the knowledge of another method to put only the logo of the wiki in open?
Many thanks,
Albert

**Comment by splitbrain** [comment]
> I don’t can put the wiki namespace (My logo is there) open or in read mode because I have some important wikis in the wiki namespace.

Don't do that. the wiki namespace is for wiki meta stuff only. Do not put your content there.
