### ISSUE TITLE
"Table of Contents" don't show anymore

### ISSUE THREAD

**Issue by derNachtigall** [cosmocode/dokuwiki-template-sprintdoc#72]
Hello!

I have an issue with the "Table of contents" - "TOC" on the right side.
The options are set to "toptoclevel" to 1, the "tocminheads" to 1 and the "maxtoclevel" to 5.

There is nothing shown in there:
![image](https://user-images.githubusercontent.com/82820412/115244238-0b92d980-a124-11eb-9b98-49c381b6293a.png)

If I open the configuration manager or when i save the configurations, they show up for a second:
![image](https://user-images.githubusercontent.com/82820412/115244415-354c0080-a124-11eb-90f0-f32c6e4b018b.png)

I've already tried to deactivate all plugins, but it didnt work. When I change the template to dokuwiki, arctic or anything else the TOC works normally.  All plugins, the dokuwiki itself and the template are completely updated.

Best regards,
derNachtigall

**Comment by splitbrain** [comment]
> If I open the configuration manager or when i save the configurations, they show up for a second

And then they vanish? Sounds like some javascript (or browser extension) interfering. Maybe an interaction with some plugin.

Since this is working for me (and others) I'm closing this.
