### ISSUE TITLE
struct / structstatus plugin integration in page attributes

### ISSUE THREAD

**Issue by CircleCode** [cosmocode/dokuwiki-template-sprintdoc#79]
I'd like to be able to display struct values in the page attributes zone (at least page status according to structStatus plugin)

Ideally, this would display the status only in attributes (and not in page footer).

Is this something that could be achieved?
If this can be achieved, and you do not want to develop it for now, would you accept a merge request for this?
and if you're open to a merge request, do you have some advice on where to start, and on some things I should be aware of before starting (I've never contributed on dokuwiki, but I'm familiar with php)?

I'm not sure I would have enough time to progress on this, but I'd like to try if it is okay for you.

**Comment by splitbrain** [comment]
Sure, a sensible PR would be welcome.
