### ISSUE TITLE
Some links on the sidebars are not working anymore

### ISSUE THREAD

**Issue by kavodao** [cosmocode/dokuwiki-template-sprintdoc#80]
Many links written on the sidebars are not working anymore. I switched to another template and it works fine. Then I desinstall and reinstall sprintdoc. The problem is still there.

**Comment by splitbrain** [comment]
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Please also describe what steps you took to analyze the issue and what (failed) attempts you made to fix the problem yourself.

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)
