### ISSUE TITLE
Specify local SVG icons in sidebar doesn't work

### ISSUE THREAD

**Issue by gatonero** [cosmocode/dokuwiki-template-sprintdoc#85]
Local SVG icons don't show up in the sidebar. All icons are readable by "all". For example I have an icon adjustments.svg in the main namespace. I adress it like following:

`====== Adjustment @adjustments.svg ======`
or
`====== Adjustment @:adjustments.svg ======`
Both are not shown.

For testing purposes I included `{{ :adjustments.svg |}}` in the sidebar, which is shown

![sprintdoc-local-icons](https://user-images.githubusercontent.com/8248255/145852335-0541cb73-b43a-480b-a2de-76714cafaf56.png)
.

**Comment by splitbrain** [comment]
please attach the SVG file here

**Comment by gatonero** [comment]
SVG upload is not supported. You wil find the file on gdrive. [https://drive.google.com/file/d/1gWDtFjRWHaAjnlczpdWGHZkLqbo8coOx/view?usp=sharing](url)
SimpleXML support is enabled.

**Comment by splitbrain** [comment]
Only single path SVGs are supported for embedding in the menu. You should merge the paths.

**Comment by gatonero** [comment]
Thanks a lot, it works! :-)
I followed the instructions on https://graphicdesign.stackexchange.com/questions/147506/inkscape-to-convert-multiple-paths-into-one-single-path
