### ISSUE TITLE
Icons in sidebar broken with Php8

### ISSUE THREAD

**Issue by rebeka-catalina** [cosmocode/dokuwiki-template-sprintdoc#96]
When I use the Sprintdoc template in Dokuwiki with Php8 the icons in the sidebar's collapsible parts -
like ```===== Public @earth.svg =====``` - gets broken after a few page refreshs and are displayed this way on my installation:

![menu-icons](https://user-images.githubusercontent.com/7385838/214216991-87a4f14c-8d3b-4560-9f48-b56c54194cc8.jpg)

This happens only in the sidebar menu. When I use - for example - the icons plugin in wiki pages, icons are displayed correctly. This happens only when I use Dokuwiki with php8.

**Comment by splitbrain** [comment]
I cannot reproduce this. Please provide more details. What happens when you open `https://yourserver/lib/tpl/sprintdoc/svg.php?svg=lan.svg&e=1`? Any error logs?

**Comment by fiwswe** [comment]
Hmm, on my DW 2022.07.31a "Igor", PHP 8.1.14, sprintDoc Template 2022-10-09 I get:

```
<svg width="" height="" viewBox="0 0 24 24"><path d="M10,2C8.89,2 8,2.89 8,4V7C8,8.11 8.89,9 10,9H11V11H2V13H6V15H5C3.89,15 3,15.89 3,17V20C3,21.11 3.89,22 5,22H9C10.11,22 11,21.11 11,20V17C11,15.89 10.11,15 9,15H8V13H16V15H15C13.89,15 13,15.89 13,17V20C13,21.11 13.89,22 15,22H19C20.11,22 21,21.11 21,20V17C21,15.89 20.11,15 19,15H18V13H22V11H13V9H14C15.11,9 16,8.11 16,7V4C16,2.89 15.11,2 14,2H10M10,4H14V7H10V4M5,17H9V20H5V17M15,17H19V20H15V17Z" /></svg>
```
Not sure about the empty values for the width/height attributes? And the browser complains: `This XML file does not appear to have any style information associated with it. The document tree is shown below.`

The SVG seems fine though. I can view the resulting image in a different application (BBEdit preview window).

fiwswe

**Comment by splitbrain** [comment]
> XML Parsing Error: not well-formed

This is a result of the error, not the error itself. Try to see if you get any error logs. Might also be a firewall/proxy problem if there's anything meddling with your traffic between your wiki server and github, the download of the original SVG might have failed.

**Comment by rebeka-catalina** [comment]
I close this issue, because it turned out to be a local issue.

I'm sorry for this.
