### ISSUE TITLE
Edit section feauture get's lost when using php8

### ISSUE THREAD

**Issue by rebeka-catalina** [cosmocode/dokuwiki-template-sprintdoc#97]
The buttons in Sprintdoc template to edit pages' sections get lost when switching to php8.

I use (and need) this feature a lot. I really want to run my Dokuwiki installation with php8 now, so for now I use another template, because especially on large and/or complex pages I need the ability to edit a section only.

**Comment by splitbrain** [comment]
I cannot reproduce this. I'm closing this. Feel free to add more details for a reopen.
